### ISSUE TITLE
Add support for Android homescreen icons

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-web2#355]
We've recently added support for iOS icons to the website, however we've not added icons for Android.
At the moment, I believe Chrome will fall back to use the apple-touch-* icons, but that support is slated to be removed.

Add 192x192 and 128x128 icons to the <head> on all pages.
Ref: https://developer.chrome.com/multidevice/android/installtohomescreen#icon

----

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-702

**Comment by limenet** [comment]
@liam-wiltshire could you please provide a 192x192 version of the favicon?

**Comment by liam-wiltshire** [comment]
Not at home at the moment, have asked on IRC if anyone can sort. Thanks for contributing! :-)

**Comment by heiglandreas** [comment]
Have a looks at https://joindin.jira.com/secure/attachment/13900/android-icon-192x192.png ;)

**Comment by limenet** [comment]
@heiglandreas thank you!
