### ISSUE TITLE
If you login on /not-allowed, you go back to that page

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-web2#356]
If you try to perform an action that you should be able to, but if your session has been removed or you've been logged out, you are redirected (correctly to /not-allowed). However, if you then re-login on that page (using username/password), you are redirected back to /not-allowed, which make it look like whatever action you were trying to perform is still disallowed.

I would suggest that when we redirect someone to /not-allowed we keep a track of their previous page, and then re-route them back to that page if they login.

---

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-701

**Comment by Lakshya1605** [comment]
Hello i am new to open source and would love to contribute can someone get me started

**Comment by liam-wiltshire** [comment]
Hi @Lakshya1605 we'd love to get you started! Best thing to do is grab one of us on IRC. I'm out this eve, but if you join #joind.in on freenode, we can get you started!

**Comment by lucianoqueiroz** [comment]
Do you have any example of a not-allowed action? I wasn't able to reproduce this issue :/

**Comment by lucianoqueiroz** [comment]
@liam-wiltshire This particular issue I fixed, the others 'not-allowed' usage seems to be already using "?redirect" parameter

**Comment by lucianoqueiroz** [comment]
#372
