### ISSUE TITLE
Improve element alignment

### ISSUE THREAD

**Issue by heiglandreas** [joindin/joindin-web2#358]
Via Marco Pivetta:
elements seem to be a bit misaligned (notice the @ symbol in http://marco-pivetta.com/screen/caps/9fe346.png, see the buttons in http://marco-pivetta.com/screen/caps/3014f4.png )
## 

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-682

**Comment by vijeth-aradhya** [comment]
@heiglandreas Can you a bit more descriptive about the issue? What do you mean by @ symbol being misaligned (with respect to what?), similarly for buttons?

**Comment by heiglandreas** [comment]
As far as I understand Marco the @ symbols in the CfP list and the Buttons in the event-list should all be under one another. 

I can second that as it would make the whole page less disturbed though I'm not sure how to achieve that as it depends very much on the content before the @ or the button. 

One possibility IMO would be to add a third line or to change the positions of the different elements.
