### ISSUE TITLE
Time picker throws warnings for single-digit times in Chrome

### ISSUE THREAD

**Issue by heiglandreas** [joindin/joindin-web2#359]
When you try to create a talk using Chrome, the time-picker doens't update the input field if the hour is single digit (e.g. 9:00, 8:30 etc).
The console throws the following warning:
""The specified value "9:15" does not conform to the required format. The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.""
If the hour is a double digit hour (10, 11 etc), it works fine.
Works even with a single digit hour in Firefox

--

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-697

**Comment by liam-wiltshire** [comment]
@heiglandreas  think this has already been claimed in JIRA?

**Comment by heiglandreas** [comment]
Yeah. Seen that to late ;)

This way @cal-tec can reference this Issue from his PR.. (yes, I know it's a lame excuse)

**Comment by Jean85** [comment]
The PR is merged! Is the #364

**Comment by railto** [comment]
My Bad, I thought I had closed this issue when I accepted the PR, closed now.
