### ISSUE TITLE
Adding the name of the event to the reported comment emails

### ISSUE THREAD

**Issue by heiglandreas** [joindin/joindin-web2#360]
Now that Joind.In is widely used, if I am an organiser for multiple events, there is no way of knowing when a comment report comes in what event it relates to.
We have added a link to the reported comments screen now to make this easier, however having the event name in the email as well would be nice.
NOTE: This is needed in two emails - Reported Talk Comment and Reported Event Comment - both are handled by different services and different email templates.

---

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-699

**Comment by railto** [comment]
Closing as was completed already
