### ISSUE TITLE
Single quotes escaping

### ISSUE THREAD

**Issue by garak** [joindin/joindin-web2#366]
I tried to insert a talk where a speaker's name contains a single quote (e.g. `D'Amico`). The speaker name is then shown with incorrect escape (e.g. `D&#39;Amico`)

**Comment by Jean85** [comment]
Did you reproduce the issue in the local dev environment or onto the live site?

**Comment by garak** [comment]
Live website. You can see it here https://joind.in/event/symfonyday-italy-2016/schedule/list

**Comment by gjuniioor** [comment]
@garak I had visited this link right now and it's ok. Can you confirm it?

**Comment by garak** [comment]
Yes, thanks!
