### ISSUE TITLE
Text inputs mangled

### ISSUE THREAD

**Issue by ihabunek** [joindin/joindin-web2#378]
When adding a talk, for data entered in text inputs:
- `'` is replaced with `&#39;`
- croatian characters `đčć` are replaced by `?`

![image](https://cloud.githubusercontent.com/assets/482138/19729241/a295af76-9b96-11e6-97c8-1f7f272afcb5.png)

This manifests in talk title, description and speaker name inputs, probably in others too.

This does not happen in web1.

**Comment by Jean85** [comment]
Maybe it's the same issue of #366 ?

**Comment by ihabunek** [comment]
Seems so. But that one is closed...

**Comment by heiglandreas** [comment]
Strange. I just checked with my browser (Safari 10.0.1 on OS X Yosemite 10.10.5) and got this result:
![screenshot](https://cloud.githubusercontent.com/assets/91998/19734443/d8daa27e-9ba7-11e6-8c82-83e309dd1085.png)

Did you change anything?

**Comment by Jean85** [comment]
Win10, Chrome 53, I'm getting the same (good) result.. It seems browser dependant, maybe some HTML meta for the characters encoding?

@ihabunek what's your OS/browser?

**Comment by ihabunek** [comment]
@Jean85 Win10, tried with Opera, Chrome, Firefox and IE. Linux tried with Opera. I think I had the same problem going through API, but don't have time to test this week.

The test was: create a new talk titled `foo`, then rename it to `foo'` in each browser.

![image](https://cloud.githubusercontent.com/assets/482138/19755377/c27f3580-9c15-11e6-80e5-01fa64271aa4.png)

The result is the same on all above mentioned browsers:

![image](https://cloud.githubusercontent.com/assets/482138/19755385/d36fe24a-9c15-11e6-9d38-a538b0bd9642.png)

I have removed this test talk, because our conference is tomorrow and I don't want test data there.

I have Croatian locale set up, but that should make no difference, especially for `'`.

**Comment by ihabunek** [comment]
@heiglandreas From the source, for the test mentioned above ^

```
<title>foo&amp;#39; - WebCamp Zagreb 2016 - Joind.in</title>
```

```
          <h1>
                foo&amp;#39;
                                    <span id="webcamp-zagreb-2016/foo39" class="star-wrapper">
                        <a href="javascript:" class="talk star">&#10025;</a>
                    </span>
                            </h1>
```

Apparently, the talk title is escaped twice.

**Comment by heiglandreas** [comment]
Looking at that last frisby-test added it looks like the escaping issue is something dug into the API. I'll see how to fix is, especially as it seems to be only an issue for talk titles and not for event-titles…

**Comment by ihabunek** [comment]
Cool that you reproduced it. It also happens in other talk fields, such as description, speaker name.

I hope to contribute some code as well, but right now I have a conference to set up. :)

**Comment by heiglandreas** [comment]
You take care of the conference and I'll take care of the quotes 😉 

I think I already found the issue! Looks like an easy fix 😄

**Comment by ihabunek** [comment]
Yes I fixed it on legacy web.

-- Ivan



On Wed, 26 Oct 2016, at 18:13, Andreas Heigl wrote:
> Strange. I just checked with my browser (Safari 10.0.1 on OS X
> Yosemite 10.10.5) and got this result: screenshot
> Did you change anything?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>

Links:

  1. https://github.com/joindin/joindin-web2/issues/378#issuecomment-256399267

**Comment by ihabunek** [comment]
@heiglandreas I finally managed to set up the dev environment. :) 

I see you fixed the double escaping of the quotes. In the meantime I found the problem with non-ascii characters.

The problem lies in this line:
```php
$ji_db->query('SET CHARACTER SET utf8');
```

Located here:
https://github.com/joindin/joindin-api/blob/06db1b0a9c8e0b4b0214960406d881ee3f560a6f/src/public/index.php#L51

If this line is removed, the UTF8 encoding works.

## Quoting [the manual](http://dev.mysql.com/doc/refman/5.7/en/charset-connection.html):

A SET NAMES 'charset_name' statement is equivalent to these three statements:

```
SET character_set_client = charset_name;
SET character_set_results = charset_name;
SET character_set_connection = charset_name;
```

SET CHARACTER SET is similar to SET NAMES but sets character_set_connection and collation_connection to character_set_database and collation_database. A SET CHARACTER SET charset_name statement is equivalent to these three statements:

```
SET character_set_client = charset_name;
SET character_set_results = charset_name;
SET collation_connection = @@collation_database;
```

## Conclusion

If you check your `@@collation_database`, you will see that it is `latin1`. Therefore, SET CHARACTER SET will override the `collation_connection` to `latin1`, and that is the cause of this issue. Since SET NAMES is already called in [line 50](https://github.com/joindin/joindin-api/blob/06db1b0a9c8e0b4b0214960406d881ee3f560a6f/src/public/index.php#L50), the charset is configured properly, and it's safe to delete this line.

**Comment by heiglandreas** [comment]
I'd rather avoid removing that call and instead set the database to the correct values. But that's nothing I can do but that needs to be done on the server side by an admin. @magicmonkey might be able to give us more insight here?

**Comment by ihabunek** [comment]
Ok, I agree that you should change the database encoding, but also check individual tables, some are utf8, some are latin1. I'm not sure what's entailed in changing the charset of a table. [Here](http://stackoverflow.com/questions/1049728/how-do-i-see-what-character-set-a-mysql-database-table-column-is#1049958) is code i used to check table encodings.

I'm not sure why you would keep both SET NAMES and SET CHARACTER SET, since they are redundant according to the manual. 

Furthermore, you don't event need SET NAMES, since the [MySQL DSN](http://php.net/manual/en/ref.pdo-mysql.connection.php) has the `charset` parameter which handles this.

So you could just do something like:

```php
$pdo = new PDO("mysql:host=$host;dbname=joindin;charset=utf8", $user, $pass);
```

Just tried it out on vagrant and it works. And saves you 2 queries per request.

But hey, in the end, as long as this issue is fixed i'm happy. :)

**Comment by heiglandreas** [comment]
From what you wrote, SET NAMES and SET CHARACTER SET are **similar** not equal.

SET NAMES sets the *character-set* of the connection, SET CHARACTER SET sets the *collation* for the connection.

I'm pretty sure the SET NAMES is a relict from old days where the charset-part of the MySQL DSN was silently ignored when present. 

Nevertheless I'd like to have the opinion from someone with access to the live-DB to be sure what's happening there.

**Comment by ihabunek** [comment]
Sure, I'm happy to wait for a person who knows what he's talking about.
