### ISSUE TITLE
Missing slides link in talk page

### ISSUE THREAD

**Issue by garak** [joindin/joindin-web2#425]
I added slides to my talk, but link (to slides) does not appear in the talk page

Event page (with link): https://joind.in/event/symfonyday-italy-2017/schedule/list
Talk page (**without** link): https://joind.in/event/symfonyday-italy-2017/disinstallare-fosuserbundle-e-vivere-felici
Legacy talk page (with link): https://legacy.joind.in/talk/view/22637

**Comment by exussum12** [comment]
Were the slides uploaded on legacy ?

**Comment by garak** [comment]
Yes

**Comment by heiglandreas** [comment]
Hey @garak. Would you mind uploading the slides (again) on https://joind.in/event/symfonyday-italy-2017/disinstallare-fosuserbundle-e-vivere-felici ? That would solve the issue for you.

Why is that so? 
A while ago we added the possibility to add more than slides. That caused a complete change in the underlying database. We also included a way to be able to display the uploaded slides in the "legacy" app. As we don't develop for the legacy-app any more that change was not ported. But we should have disabled the possibility to upload slides on legacy at all to circumvent that issue… Looks like there is an issue we need to solve!

**Comment by garak** [comment]
I did as suggested, now it works.
Thanks!

**Comment by exussum12** [comment]
@heiglandreas The api call was left in (and the column etc) to be able to handle this. I will take a look to see why the original call doesnt work.

Thinking more about it I can remove the column too. and just have it all flow in to the new structure

**Comment by heiglandreas** [comment]
Take care @exussum12 - The event-page seems to display the slides link from the "wrong" source… Something is rather fishy there…
