### ISSUE TITLE
The act of Reporting a comment, does not require confirmation.

### ISSUE THREAD

**Issue by kenguest** [joindin/joindin-web2#428]
I would expect to be asked for confirmation when clicking to report a comment on a talk - what happens, for example, if I accidentally click to report the wrong comment?

At least if asked for confirmation, that might display an excerpt of the comment in the confirmation screen, about to be reported then there would be some degree ensuring the incorrect comment is not deleted/withdrawn.

True story - this happened to a comment I posted on a talk over the weekend, when I went back to see how others thought of the talk I thought someone intentionally deleted the comment because it was "only a two-star" :-)

**Comment by eleftrik** [comment]
@kenguest Today I accidentallly posted a two star comment instead of a five star. It's frustrating, I couldn't find any way to modify or delete my comment. It's silly.

**Comment by czmole** [comment]
Added PR for a basic confirmation #441

**Comment by railto** [comment]
As the patch for this was merged I'm going to close this ticket now, thanks for reporting it.
