### ISSUE TITLE
"Page not found" when clicking on my name

### ISSUE THREAD

**Issue by warren5236** [joindin/joindin-web2#433]
I apologize in advance if this isn't the correct venue for this but when I click on my name in the menu I receive an error that the page isn't found.  The URL shows up as https://joind.in/user/1.0155671600264E+16

**Comment by exussum12** [comment]
Where is this linked from ?

**Comment by warren5236** [comment]
I can duplicate it from https://joind.in/event/midwest-php-2018 and https://joind.in/event/midwest-php-2018/community

**Comment by exussum12** [comment]
Did you sign in with Facebook ?

**Comment by exussum12** [comment]
Think I know the fix. I will be able to look at next week. Moving house ATM

**Comment by warren5236** [comment]
>Did you sign in with Facebook ?

Yes

>Think I know the fix. I will be able to look at next week. Moving house ATM

No rush I'm not going to be using the site for a while.  :-)

**Comment by warren5236** [comment]
Thanks for creating this BTW.  It was a great resource at the conference.

**Comment by exussum12** [comment]
Found and fixed the issue. I don't have internet hooked up so will submit a pr when I can. It's in a few places.
