### ISSUE TITLE
Speakers at an event should be marked as "attending"

### ISSUE THREAD

**Issue by eryno** [joindin/joindin-web2#434]
## Steps to reproduce
1. Submit a claim for a talk
1. Claim is accepted
1. Go to details page for the event (`https://joind.in/event/EVENT_SLUG/details`)

# Expected result
I will be marked as having attended ("35 attended `including you`").

# Actual output
I am not included in the attendees ("34 attended `I went to this event`").

**Comment by exussum12** [comment]
Pull request added in the API

**Comment by railto** [comment]
Thanks for the suggestion @eryno and @exussum12 for implementing it, unfortunately, I'm a lil slow to close out these issues, but I'm getting there.
