### ISSUE TITLE
JOINDIN-499: Add the ability to view listings of past events.

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#569]
Jira issue originally created by user phoenix:

At the moment when navigating to /event it's displaying the list of upcoming events, but there is no exposed ability to be to view a listing of events that have already past. This would be useful for people looking for events to go to.

As way to implement this, I would like to see a new filter on the /events endpoint that that defaults to upcoming events from today which supplies previous and next links to allow retrieving events in the past or in the future from this single filter. 

From a web2 point of view, this would be mean that the default view on /event would show events from today forwards and there would be backwards and forwards links at the bottom. 

i.e. I would prefer not to have to think if I want previous or upcoming - I just want one list where the start point is "today".

**Comment by heiglandreas** [comment]
This is by now already implemented (for quite some time actually). The Events-Site starts with todays date but has previous and next buttons underneath it.
