### ISSUE TITLE
JOINDIN-527: Import talks via CSV

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#586]
Jira issue originally created by user akrabat:

An event admin needs to be able to import talks via a CSV file.

An import should create a number of Talk-Drafts. A talk draft does not need to have all fields as they might not be available at that moment. Those talk-drafts should then be available to refinement. When all necessary values are available it is possible to move a draft to a talk. 

It should be possible to import Different file-formats and contents

**Comment by EliW** [comment]
Adding voice.   The original CSV upload was one of the best features of joind.in -- And IMO it's basically unusable without this.   As an event organizer I really don't want to be spending hours entering 30-60 talks manually one by one.

An awesome feature update would be to not only allow upload, but to take a page from every existing mobile-app-that-does-this feature.  And have a button that would also allow for download of existing data.  So you can modify them and reupload.

But just getting initial upload working again, would be amazing.

**Comment by EliW** [comment]
Tagging @svpernova09 Just because I realized that no-one was tagged at all because joindin-bot.  So not sure anyone will have seen my comment.

**Comment by iansltx** [comment]
Saw your reply earlier :) I believe all of the leadership team gets tagged when issues or filed or replies posted. I'll have to defer on this to folks 'til after this weekend.

**Comment by heiglandreas** [comment]
I had this idea of a CLI tool that can read a CSV and add the content as talks to joind.in via the API...

**Comment by EliW** [comment]
> Saw your reply earlier :) I believe all of the leadership team gets tagged when issues or filed or replies posted. I'll have to defer on this to folks 'til after this weekend.

Nice to know.  Wasn't sure how it was setup :)

**Comment by EliW** [comment]
> I had this idea of a CLI tool that can read a CSV and add the content as talks to joind.in via the API...

Neat idea @heiglandreas - But really not what a SAAS offering should provide.  There should just be a simple link to 'upload CSV here', and it inject them.  If you want people to be using the website in general, and have it be useful and full of data :)     While 'download this tool, hook up your API key, use it this way, etc' is a nice geeky solution for us coders.  It's not IMO the solution that's being provided for average user.

**Comment by heiglandreas** [comment]
There's no need for "the average user" to upload CSVs. The main idea would be to include an automated upload of talks from a CfP system via API calls. So you would not need to export a CSV from your system but instead klick a button on the selected talk and everything is sent to the API. So the CLI would be an example implementation that could be used as fallback

**Comment by heiglandreas** [comment]
But as those CfP systems are not within our reach there's little we can do apart from said example implementation.

**Comment by EliW** [comment]
> There's no need for "the average user" to upload CSVs. The main idea would be to include an automated upload of talks from a CfP system via API calls. So you would not need to export a CSV from your system but instead klick a button on the selected talk and everything is sent to the API. So the CLI would be an example implementation that could be used as fallback

My apologies, I misspoke there.  I meant 'average conference organizer' of course.  Not of course that an attendee would be doing that.

However, joind.in is unique, where it's not important (essentially) for joind.in to focus it's features on the 'con attendee' as much as on the 'con organizer' IMO.  As if you can't convince the con organizer to use it, then you don't get the users anyway.

As a con organizer, asking for all the talks to be manually input for a 3-day long 4-track wide event for example (Let alone if you wanted to get big events like OScon or DrupalCon).  Is a tough sell.   When a simple CSV import, as existed before is a clean solution.

Also by average, I meant that many of the conferences on joind.in are not 'programmer events run by programmers'.  But as it begins to appeal to a greater audience, you get con organizers for Dentist Conventions for example.  Where they may love the idea of a CSV import.  But don't have API knowledge to use a downloadable tool.  #2cents

**Comment by heiglandreas** [comment]
Fixed with #809
