### ISSUE TITLE
JOINDIN-534: Review use of json_decode

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#592]
Jira issue originally created by user lornajane:

Please review the web2 codebase and look at everywhere that we use json_decode().  In particular, for each case:
 - should this be an array?  Pass a second parameter of TRUE rather than returning an object and then casting it
 - why are some of these NOT expected to be arrays?

**Comment by exussum12** [comment]
Just checked these out, Looks like the children are expected to be objects, this way returns an array of objects (casting top level) vs an array or arrays.

Would imagine this can be closed as the two cases here would not be identical. 
Thoughts @dstockto @heiglandreas
