### ISSUE TITLE
JOINDIN-637: With the move to web2, we're re-implementing talk claims

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#654]
Jira issue originally created by user lornajane:

Talks are entered by organisers and given by speakers.  A talk should only be linked to a speaker's account if both organiser and speaker authorise this.  Either one can go first, and the other one must then approve.

When an organiser adds speakers to a talk, in addition to the current display name, they should be able to search for a user by name or username, and add the user to the talk as a speaker.  When a talk has multiple speakers, each chosen speaker needs to be linked to a display name on the talk.  The speaker will then be notified and given a link to authorise the claim.

If a talk has a speaker that is not linked to a user account, then the option to claim the talk will be offered to logged-in users.  Talks with more than one speaker will require the user to indicate which of the unlinked speaker they are.

Once the link has been created and approved, the display name of the speaker will be the display name associated with the linked user account.

Users and organisers should be able to unlink claims at any time.

Admins should also be able to do everything users can do.

**Comment by exussum12** [comment]
@dstockto @heiglandreas just confirmed this, This can be closed
