### ISSUE TITLE
JOINDIN-677: Double escaping

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#673]
Jira issue originally created by user akrabat:

Reported via feedback form:

Hi all, new site design looks awesome.

Little feedback: Looks like the output escaping is a bit too aggressive:

See: https://joind.in/event/polderphp---fourth-edition-for-real-this-time/how-to-make-good-code-great---dotting-your-i39s-and-crossing-your-t39s
Displayed: How to make good code great - Dotting your i's and crossing your t's

Should be: How to make good code great - Dotting your i's and crossing your t's

**Comment by exussum12** [comment]
@dstockto @heiglandreas this has been resolved
