### ISSUE TITLE
JOINDIN-682: Improve element alignment

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#676]
Jira issue originally created by user akrabat:

Via Marco Pivetta:

elements seem to be a bit misaligned (notice the  symbol in http://marco-pivetta.com/screen/caps/9fe346.png, see the buttons in http://marco-pivetta.com/screen/caps/3014f4.png )

**Comment by heiglandreas** [comment]
As the original screenshots are not available anymore this is currently not fixable. I'll close it hereby.
