### ISSUE TITLE
JOINDIN-690: Redirection after login via twitter API is only to home page

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#682]
Jira issue originally created by user tessbarnes:

When timed out, post of a comment fails with error or site displays log in side bar.
when logging in via TwitterAPI from any page web2 site does not return to selected page but redirects to home page on OAUTH/2 confirmation.

1) review current redirection behaviour to check if simply missing from this scenario
2) review tests required for project in this area
3) evaluate possible approach for this scenario: http://stackoverflow.com/questions/7722062/google-oauth2-redirect-uri-with-several-parameters
4) ensure that any data passed is secured in the accepted way for web 2 to match any other implementations in the project e.g. base64 encode / decode

**Comment by heiglandreas** [comment]
This is already implemented. I'll close it therefore.
