### ISSUE TITLE
JOINDIN-698: Trying to report a comment from the 'Talk Comments' page fails

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#689]
Jira issue originally created by user liam-wiltshire:

When I visit the talk comments page of an event (e.g. https://joind.in/event/laracon-eu-2016/talk-comments), the link to report a comment is wrong 

Following the example above, the given URL to report the comment by "Alexander Feil" on "Curing The Common Loop" is https://joind.in/event/laracon-eu-2016/comments/d77a82/report

whereas if you go to the talk itself and lookup the same comment, the report URL should be https://joind.in/event/laracon-eu-2016/curing-the-common-loop-with-collection-pipelines/comments/d77a82/report

The hash etc is correct, it's just missing the talk 'slug'

**Comment by exussum12** [comment]
@dstockto see comments above. Fix merged @heiglandreas
