### ISSUE TITLE
JOINDIN-728: Handle Web2 API keys better

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#703]
Jira issue originally created by user akrabat:

1. The page at https://joind.in/user/{apikey}/apikey should not display web2 keys
2. There should only be one web2 key. i.e. the old ones should be deleted and I should not see: https://i.19ft.com/8a5fe019.png

**Comment by exussum12** [comment]
@dstockto @heiglandreas  This is API side, There is a ticket already open can close web2 ticket
