### ISSUE TITLE
JOINDIN-741: Registration via Github/Twitter/Facebook

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#710]
Jira issue originally created by user esurov:

It really confused me that I can't log in to joind.in with my github or twitter/facebook. I just wanted to rate a talk while having 5-minutes break, so it had to be really fast. I didn't have any joind.in account and thought I could create one in a second clicking signin with Github. But there was no error message like you need to Register first filling in a form. It just gave me Login Failed and I thought that website is broken.

**Comment by exussum12** [comment]
Facebook has been resolved there is an open or for GitHub. So can also be closed @railto ?
