### ISSUE TITLE
JOINDIN-747: Approving pending talk claim fails

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#714]
Jira issue originally created by user madasha:

As an existing user (username: madasha) I am attempting to approve a claimed talk from the following event: https://joind.in/event/bulgaria-php-2016

The talk URL: https://joind.in/event/bulgaria-php-2016/scaling-php

I go to https://joind.in/event/bulgaria-php-2016/claims, click on the [Approve] button, and I get a 500 ISE error ("We're sorry, but an error occurred.").

Here's the cURL POST request representing the form submission:
```
curl 'https://joind.in/event/bulgaria-php-2016/claims' -H 'Content-Type: application/x-www-form-urlencoded' --data 'talk=2ea0c&display_name=Dustin+Whittle&username=dustin.whittle&action=approve'
```

Here's the response headers:
```
HTTP/1.1 500 Internal Server Error
Date: Sat, 10 Jun 2017 09:20:48 GMT
Server: Apache
X-Powered-By: PHP/5.6.4
Cache-Control: max-age=0
Expires: Sat, 10 Jun 2017 09:20:48 GMT
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1926
Connection: close
Content-Type: text/html;charset=UTF-8
```

Additional info: Using Firefox 53.0 under Ubuntu. Have in mind that the event took place relatively long time ago (Oct 2016) and I've forgotten to approve that talk then.

**Comment by exussum12** [comment]
I fixed this a while back @dstockto @heiglandreas
