### ISSUE TITLE
JOINDIN-751: Please add a "Duplicate Talk" button in the same region as "Edit talk" and "Delete Talk" - perhaps for administrators only?

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#718]
Jira issue originally created by user jontheniceguy:

This option would create a new entry for the schedule, suitable for re-submission (useful for, for example, unconferences which need lots of "Unconference" talks). Perhaps add some logic which notices whether no details have been changed to prevent submission of lots of exact duplicates.

**Comment by exussum12** [comment]
Should the un conf talk not be the name of the talk ? Im not sure I see a purpose in this
