### ISSUE TITLE
JOINDIN-755: Joind.in logins expire very quickly

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-web2#721]
Jira issue originally created by user jontheniceguy:

The joind.in logins expire (subjectively) very quickly. I would expect to log in at the start of an event, and for the login to not expire until I close the browser... if that soon! It currently feels like the login expires in around 15-30 minutes.

**Comment by exussum12** [comment]
This has been resolved @railto

**Comment by railto** [comment]
Indeed it has, thanks
