### ISSUE TITLE
Add easy pick label

### ISSUE THREAD

**Issue by exussum12** [joindin/joindin-web2#735]
Can someone add an easypick label similar to the one in JIRA ?

**Comment by exussum12** [comment]
Can this be added to API too please ? Same spelling etc

**Comment by heiglandreas** [comment]
Ping @dstockto / @liam-wiltshire

**Comment by dstockto** [comment]
Added easy-pick labels to projects where issues are enabled.

**Comment by exussum12** [comment]
Great thanks :)
