### ISSUE TITLE
Discontinue hosted project

### ISSUE THREAD

**Issue by lornajane** [joindin/joindin-web2#739]
After 10 years of serving tech events everywhere, joind.in is sad to announce that it will no longer be available after 31st March 2019.

In recent years, we have been short on volunteer effort and heavy on tech debt. As an open source code project, this is not a problem, others can always fork and take up the torch. For a hosted product, it is a big problem. At this point, the project needs major time investment, new servers, updated tooling, and a whole team of owners and maintainers - and it does not have them. Those of us still involved in the project have agreed that we are no longer comfortable keeping the servers online as things stand.

**Q: Why is this happening now?**

A: It should have happened a while ago if we're honest, we just didn't take this step before. It's the Right Thing (TM) to do and we think that "now" is always a good time to do the right thing.

**Q: What about my data?**

A: We'll put up a read only version of the API so that the community's data is still available. As well as individual's talk portfolios and their feedback, joind.in holds all the conference schedules of many, many events. We have always considered ourselves caretakers of community data and we'll continue to make what we have available.

**Q: Will you delete my account?**

A: Yes, please email info@joind.in from the email address you registered with. If you've requested this before but didn't get a confirmation email, please email us again. This is a manual process, so be patient!

**Q: My event relies on joind.in, what can I do?**

A: We don't know. People mostly rely on joind.in for public feedback about the sessions at their event and an excellent, mobile-friendly version of a schedule. Speakers use it as their portfolio. If you know of alternatives, let us know and we'll share them.

**Q: Is this about money?**

A: No, we don't have any of that. A special mention goes to the various sponsors who have supported us over the years, especially Combell who have shouldered our server costs for most of that time, but also others who chipped in for domain names, SSL certs, and that sort of thing.

**Q: Can I run my own version of joind.in?**

A: You certainly can, it's open source.

**Q: Can I help?**

A: Probably not. At this point joind.in needs more than help. It needs a team of people including dev and ops skills, data management and general ongoing attention. It also needs ownership and leadership. If you can assemble all of the above with people who know and love joind.in and want to take it forward, of course you should get in touch!

**Comment by exussum12** [comment]
Happy to help out with what ever is needed. Thanks everyone for their efforts with joind.in

**Comment by driesvints** [comment]
Thanks @lornajane and everyone involved for all the years of dedication and work you've put into this. Really appreciate the effort from you all for the community.

**Comment by ravage84** [comment]
@lornajane sad to hear. Could the team make sure that all public content of joind.in is crawlable/scrapable for the [Wayback Machine](https://web.archive.org/web/*/joind.in)? This way it can be preserved.

**Comment by svpernova09** [comment]
@lornajane thanks so much to you and everyone involved over the years.

I'm curious to know what it would look like if someone wanted to fork / rewrite / replace / take over. I've asked the question to start the conversation in IRC.

<3 to all of you and especially those maintainers.

**Comment by freekmurze** [comment]
Thanks to everybody involved for all the work they put in Joined. The feedback submitted to this platform certainly helped me to get better at speaking, and I hope I also helped others with feedback.

Currently discussing with my team on how we can create an alternative for this, if no one would step up to take over joined.in itself.

**Comment by heiglandreas** [comment]
@exussum12 (and everyone who is interested) Let's talk!

**Comment by EliW** [comment]
One for All Events would be interested in looking at helping keep this alive (and php[architect] as well) without it shutting down the current website ... Having some chats on our end.  But would love to chat with @akrabat and @lornajane and @liam-wiltshire about that possibility.

**Comment by iansltx** [comment]
Add me to the list of folks willing to assist in keeping the hosted version of this viable. The network effect of everyone posting reviews etc. in one place is a big deal. I can assist on dev or ops sides as long as it's clear what needs doing. @hskrasek may be able to throw a few hours at this as well.

**Comment by svpernova09** [comment]
If you're interested in being involved in the conversation of "Lets keep Joind.in Running and figure out what the next steps are" Please join this Discord so we can centralize the discussion: 
**https://discord.gg/SHYNhp**

(Sorry for discord, a new slack felt icky and I know half of you don't like IRC anymore even though it's far superior <3)

**Comment by stuartherbert** [comment]
Could I encourage a Discourse.org forum for discussing how to save Joindin, rather than Discord? It's much better as an async comms platform, and is much more acceptable in some professional circles :)

**Comment by stuartherbert** [comment]
I'm also very happy to step up and help keep Joindin alive.

**Comment by svpernova09** [comment]
@stuartherbert, I went with Discord because real time chat felt much more appropriate from a discussion forum.

**Comment by stuartherbert** [comment]
@svpernova09 what's one more Slack channel between friends? :)

**Comment by spriebsch** [comment]
Sorry to see joind.in go, but I can understand that the time has come to move on. 

Regardless of what efforts there are to build alternatives, may I suggest creating a static copy of the site, and keeping that around? There are many, many backlinks to joind.in from conference sites, also for material, plus a lot of speakers use the ratings to build credibility.

I'm sure we can find somebody taking care of hosting a few static pages. Ping me if you need help with that.

**Comment by JonoB** [comment]
Just putting this out there - I run a team of 6 devs, and may be interested in taking this over for a total re-write. Both @lornajane and @akrabat know me.

**Comment by heiglandreas** [comment]
There already is a joindin channel on  https://slack.php.ug - invites via https://php.ug/slackinvite

**Comment by DaveLiddament** [comment]
This is a real shame. At PHP-SW usergroup we've been really pushing joind.in for the past 18 months and have had engagement rates of over 20% (https://joind.in/search?keyword=phpsw). It's massively helped many of our speakers improve. 

Well done to all who worked on it and kept it going to where it is today. 

I hope it can continue in some form. As a Brit I'm already struggling with Brexit. I'm not sure I can cope with Jexit too!

**Comment by calevans** [comment]
If keeping it up is a matter of hosting, I'll step up and take care of that and the domain. (LetsEncrypt for the cert)

That would at least keep what is there online. 
=C=

**Comment by liam-wiltshire** [comment]
Hey Cal,

Thanks so much for the offer - everyone's offers of help and working towards keeping joind.in alive is awesome to see. 

It's not the hosting as such that's the problem - Combell have provided hosting foc for longer than I was involved, but maintaining that server requires time that none of us have. The build process uses an incredibly old version of Jenkins, we are behind on other updates, etc.

To host a read only API as is proposed is low risk - we put it on a new VM somewhere (maybe still on Combell, or otherwise we may be looking for offers ;)), we don't need a build process, no problem.

But to continue as an operating product requires more time (and frankly knowledge) than we have to spare to re-tool, re-host and basically bring things to where they need to be.

**Comment by iansltx** [comment]
Is there documentation of how the hosted-y bits work right now? Drop me a line privately if need be there. I realize hosting isn't the only issue here but if we're saying "this needs to be modernized in order to be visible" we need to understand how it's running now to figure out the best way to, e.g., get it running on 7.3 (including any necessary extensions), switch to a current-version framework, etc. (And do at least some of this for the legacy site as well as web2)

**Comment by skyvondave** [comment]
This answer to "Q: Is this about money?" is unclear...

A: No, we don't have any of that.

You don't have any of the necessary money? Or you don't have any of the problems with money?

It seems as if the description of the problems is not lack of time with the right people, or loss of interest, but just that there's not enough people or not the right people... which is solved by money to interested people, correct?

**Comment by coudenysj** [comment]
Hi,

We at Combell are more than willing to continue hosting joind.in.

I think it is fairly easy to generate a static version of the public site which we can host on our shared platform (which removes the hassle of updating the vps).

I think it is also possible to create a read only version of the api, but we should have a chat about that to see how we can accomplish that.

Jachim

**Comment by svpernova09** [comment]
@coudenysj Thanks!

**Comment by rawkode** [comment]
I have plenty of experience with ops a d SRE, I'm happy to take on the project to revitalise the build and delivery pipeline. 

Awesome to see others keen to help too.

Did a Discord or Discourse happen?

**Comment by liam-wiltshire** [comment]
@svpernova09 has been putting a plan together.

**Comment by lornajane** [comment]
I know there are a bunch of interested people who have already commented here, and some that have also emailed me directly that I have redirected here. Joind.in also has public IRC, slack (on php.ug) and believe it or not: mailing lists! I also see links to other locations for chat but given how many people here seem to be keen to help, is there a way for interested parties to follow along with the summary points?  Including me :)

**Comment by svpernova09** [comment]
> I know there are a bunch of interested people who have already commented here, and some that have also emailed me directly that I have redirected here. Joind.in also has public IRC, slack (on php.ug) and believe it or not: mailing lists! I also see links to other locations for chat but given how many people here seem to be keen to help, is there a way for interested parties to follow along with the summary points? Including me :)

Hi @lornajane! I pushed the conversation to Discord because I didn't want to cause confusion or disrupt IRC. You can check on our progress here: https://www.joeferguson.me/joind-in-proposal-working-group/ and view the current proposal: https://docs.google.com/document/d/1FIGRqwWDGOvKnKo8HDan90SuC13mMXz2tKf1U61DEFU

We're planning on presenting our proposal to you and the rest of the maintainers tomorrow. I have Rob and Liam's emails but I don't have yours. Feel free to email me at first name @ first name last name dot me and I'll ensure you'll receive it direct as well.

**Comment by exussum12** [comment]
I'm happy to be part of this as stated above

**Comment by svpernova09** [comment]
Announcement regarding Joind.in :D

https://joindin.wordpress.com/2019/02/04/new-joind-in-leadership-team/

**Comment by iansltx** [comment]
Believe we're underway enough on this to close this one out :)

**Comment by svpernova09** [comment]
Current Plan is to migrate hosts March 19th: https://joindin.wordpress.com/2019/03/15/joind-in-service-migration-maintenance-window/
