### ISSUE TITLE
Email Deliverability

### ISSUE THREAD

**Issue by exussum12** [joindin/joindin-web2#744]
Quick fix for email. We need an SPF record. (a TXT DNS record on the joind.in domain eg dig TXT joind.in should show it)

v=spf1 mx a:api.joind.in -all

That says MX and only the API (though in reality there is only one server so any code base can) can send email on behalf of joind.in

This should help with a large chunk of emails being sent

**Comment by exussum12** [comment]
Probably one for @heiglandreas will need DNS access

**Comment by heiglandreas** [comment]
Done!

```$ dig joind.in TXT @ns-171-c.gandi.net

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> joind.in TXT @ns-171-c.gandi.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62649
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;joind.in.                      IN      TXT

;; ANSWER SECTION:
joind.in.               1800    IN      TXT     "v=spf1 mx a:api.joind.in -all"

;; Query time: 63 msec
;; SERVER: 217.70.187.172#53(217.70.187.172)
;; WHEN: Sun Feb 03 16:16:05 CET 2019
;; MSG SIZE  rcvd: 79
```

Will need to traverse through the DNS now.

**Comment by heiglandreas** [comment]
@zghosts mentioned that "the joind.in server is sending mail through a relay server  relay.ix.mailprotect.be, so the combell spf record has to be added:
include:_spf.relay.mailprotect.be"

So Updated the record:

```
$ dig joind.in TXT @ns-171-c.gandi.net

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> joind.in TXT @ns-171-c.gandi.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27997
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;joind.in.                      IN      TXT

;; ANSWER SECTION:
joind.in.               1800    IN      TXT     "v=spf1 mx a:api.joind.in include:_spf.relay.mailprotect.be -all"

;; Query time: 99 msec
;; SERVER: 217.70.187.172#53(217.70.187.172)
;; WHEN: Sun Feb 03 16:56:13 CET 2019
;; MSG SIZE  rcvd: 113
```

**Comment by exussum12** [comment]
wow, That SPF record may as well not exist

`? for a NEUTRAL result interpreted like NONE (no policy).`

Can someone update that ? Would imagine its someone at combell ?

**Comment by heiglandreas** [comment]
So use "v=spf1 mx a:_spf.relay.mailprotect.be -all" instead?

**Comment by zghosts** [comment]
no it would be "v=spf1 mx include:_spf.relay.mailprotect.be -all"

**Comment by zghosts** [comment]
the ?all in the include isn't really important, it's not evaluated anyway if it's included from another record.
The -all on the joind.in record is the one that matters, this denies all other hosts from sending mail from @joind.in.
if we want to be really picky we could also use ip4:217.21.190.0/26 as i think this is the ip range for relay hosts, judging from the _spf.relay.mailprotect.be record

**Comment by exussum12** [comment]
Just checked the docs on that. Makes sense. I thought it was processed as if it was part of the main record itself. Cheers
