### ISSUE TITLE
Pending talk claim acceptance sometimes errors out after finishing at least the association part of claim acceptance

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-web2#757]
Will figure out a more detailed repro scenario later, but just now noticed when claiming my own uncon talk at Sunshine. Maybe that shouldn't be a thing, but the system errored out after succeeding in accepting the pending talk claim, so something's amiss with current behavior.

**Comment by iansltx** [comment]
This appears to be a broader, intermittent issue with talk claim approvals. Will look at logs to figure out what's going on.

**Comment by heiglandreas** [comment]
This should be fixed by now. AFAIK it was the Email-Subsystem. It it is not fixed, feel free to open this again.
