### ISSUE TITLE
Session cookie can be exposed over non-TLS endpoint

### ISSUE THREAD

**Issue by aenglander** [joindin/joindin-web2#769]
See: https://en.wikipedia.org/wiki/Secure_cookie.

The session cookie does not have the secure flag and will leak the session ID over non-secure transports allowing for session hijacking.

`set-cookie: PHPSESSID=2d4e9f55475f734cb00cb45d6dab14c5; expires=Sun, 10-Mar-2019 21:25:58 GMT; Max-Age=604800; path=/`

**Comment by zghosts** [comment]
Secure flag has been set on the server
