### ISSUE TITLE
Bot sending spam and I can't ban or block the user on my event

### ISSUE THREAD

**Issue by pokemaobr** [joindin/joindin-web2#789]
Hi, how are you?

I am one of the PHP Experience 2019 (https://joind.in/event/php-experience-2019) organizers that happened this weekend. We have been using joind.in for years to receive feedback from the events of the São Paulo PHP user group (PHPSP). However, we are having difficulties this time around. There is a user https://joind.in/user/mandeilins sending spam in our event and I can not ban or block this user from the event. Every time I try to report the comments it sends more spam. What can I do?

I tried to send this message on website form, but the phone field isn't working.

Thank you so much,
Rodrigo "pokemaobr" Cardoso

**Comment by iansltx** [comment]
@pokemaobr Sorry for the issues. Working on this now.

**Comment by iansltx** [comment]
@pokemaobr We've nuked the offending user's comments and deactivated them. Apologies for the show turn on this one. They had submitted 2809 (!) comments, so your event was noot the only one affected. I'm creating follow-on issues now to fix various points of failure that led to this.

**Comment by pokemaobr** [comment]
thank you so much!
