### ISSUE TITLE
Web2 404 page refers to the old legacy site

### ISSUE THREAD

**Issue by dstockto** [joindin/joindin-web2#791]
Hitting a page or link that doesn't exist gives the 404 page, but it says to try out the page on legacy.joind.in. That site isn't a thing any more.

![image](https://user-images.githubusercontent.com/775393/55695282-2cd96080-5975-11e9-93bb-d4fe6bdbc5ea.png)

**Comment by iansltx** [comment]
It looks like we've actually fixed this in https://github.com/joindin/joindin-web2/pull/787/files, but haven't deployed with that new code quite yet. @svpernova09 / @mcneely, y'all wanna do the honors?

**Comment by mcneely** [comment]
@dstockto @iansltx Deployed but not showing up. I purged Cloudflare as well but no dice so far.

**Comment by mcneely** [comment]
Ok, finally updated. I had to clear the twig cache on the container.
