### ISSUE TITLE
Made a Test talk to check something.  Error when deleting it.

### ISSUE THREAD

**Issue by EliW** [joindin/joindin-web2#804]
On an event that I submitted.  I added a test talk because I wanted to test something about how comments worked.

I couldn't comment because the event was too far out.  Makes sense.

I went to delete the test talk.  And got this error:
<img width="514" alt="Screen Shot 2019-05-02 at 2 22 15 PM" src="https://user-images.githubusercontent.com/1153183/57097478-d4804f00-6ce5-11e9-930e-8970221b5140.png">

**Comment by EliW** [comment]
Talk still exists.  And cannot be deleted.

**Comment by iansltx** [comment]
Fix for this is now live on the hosted site.

**Comment by EliW** [comment]
Confirmed, it worked!
