### ISSUE TITLE
Add Russian language to the "talk language" list

### ISSUE THREAD

**Issue by lisachenko** [joindin/joindin-web2#811]
Currently language list for the talk doesn't contain Russian language. Could you please add it as one of possible languages for the talks.

This can be generalized as adding all possible languages to the list. Thanks!

**Comment by mcneely** [comment]
I've added the language to the database. You should be good to go!

**Comment by heiglandreas** [comment]
This snippet should show **all** languages.
```php
$f = ResourceBundle::getLocales(null);
$lang = [];
foreach ($f as $language) {
    $lang[] = Locale::getDisplayLanguage($language, 'en_GB');
}
$lang = array_unique($lang);
natcasesort($lang);

print_r($lang);
```

Not sure it makes sense to have that execute on every call or once on deployment and then write the ouptut into a certain file and read that then....

**Comment by heiglandreas** [comment]
I'd definitely look forward to the first talk being held in "colognian" or "esperanto"...

**Comment by lisachenko** [comment]
Thank you for quick fix!

**Comment by mcneely** [comment]
@heiglandreas We'd have to do update the data as we're not currently using a standard other then a modified ISO-639-1 from the way it looks.

**Comment by heiglandreas** [comment]
Updated the snippet. And yes, we'd either need to modify the language-list to include en_US and en_GB or modify the DB to only use the ISO-639-1 codes
