### ISSUE TITLE
Incorrect handling of unicode talk titles 

### ISSUE THREAD

**Issue by lisachenko** [joindin/joindin-web2#815]
For the **PhpRussia19** conference we have a lot of talks in Russian language https://joind.in/event/php-russia-2019/schedule/grid. 
Unfortunately, I have noticed that platform does not support transliteration thus generated URL for talks are ugly: 
  - https://joind.in/event/php-russia-2019/-----
  - https://joind.in/event/php-russia-2019/------26228
  - https://joind.in/event/php-russia-2019/-php- 

My suggestion is to use `Transliterator::transliterate` method from `Intl` extension to perfrom transliteration of talk titles, based on talk language.

For example, for [Russian language](https://3v4l.org/1Jve2) we should use `'Russian-Latin/BGN'` transliterator:

```php
$trans = Transliterator::create('Russian-Latin/BGN');
echo $trans->transliterate("Эволюция обработки вебхука Facebook: с нуля до 12'500 в секунду"), PHP_EOL;
```
```
Evolyutsiya obrabotki vebkhuka Facebook: s nulya do 12'500 v sekundu
``` 

Is it possible to quickly add this feature and to regenerate URLs for all talks in our conference before we ask speakers to add link to joind.in

**Comment by lisachenko** [comment]
Just as quick fix: allow organizers to edit the URL field of talk from the database. Not a safe variant, but it would better than nothing )

This can be simple and useful feature to adjust errors in URLs as well, for example one of my talk: https://joind.in/event/dutch-php-conference-2016/olving-cross-cutting-concerns-in-php misses capital letter "S" in URL and there is no way to fix that.

**Comment by heiglandreas** [comment]
I'd see this as a separate issue. So I created a separate issue (#816) to track that ;-)

**Comment by lisachenko** [comment]
Is it possible to implement one of this till our conference starts? Or update tracks? Otherwise I need to manually delete each talk and add it transliterated to have nice URL and edit one more time to change title to Russian language
