### ISSUE TITLE
Unable to Add Event Without CFP Link

### ISSUE THREAD

**Issue by leesto** [joindin/joindin-web2#827]
When adding an event through the UI, the CFP URL is optional. However, not including one results in an error when adding the event.

As our meetup events don't have a CFP, it would be ideal to have this field continue to be optional

Error on submission:

`Fatal error: Uncaught TypeError: Argument 1 passed to Form\Exception\UnresolvableUrl::__construct() must be of the type string, null given, called in /app/joindin-web2/app/src/Form/Shared/UrlResolver.php on line 35 and defined in /app/joindin-web2/app/src/Form/Exception/UnresolvableUrl.php:11 Stack trace: #0 /app/joindin-web2/app/src/Form/Shared/UrlResolver.php(35): Form\Exception\UnresolvableUrl->__construct(NULL, 0) #1 /app/joindin-web2/app/src/Form/Listener/GetResolvedUrlListener.php(27): Form\Shared\UrlResolver->resolve(NULL) #2 [internal function]: Form\Listener\GetResolvedUrlListener->onSubmit(Object(Symfony\Component\Form\FormEvent), 'form.bind', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 /app/joindin-web2/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\Form\FormEvent), 'form.bind', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /app/joindin-web2/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\Event in /app/joindin-web2/app/src/Form/Exception/UnresolvableUrl.php on line 11`

**Comment by heiglandreas** [comment]
Thank you for your bug report. I already figured out what the problem is and created a fix for it. I will submit it toworrow morning, so we can have this fixed very soon!
