### ISSUE TITLE
Error & PHP Fatal Error dump (visible) on editing event without CfP link

### ISSUE THREAD

**Issue by EliW** [joindin/joindin-web2#833]
I went to edit MidDevCon, because the venue had a typo.  I changed it, hit save.  And got this:

<img width="1437" alt="Screen Shot 2019-07-11 at 8 53 21 PM" src="https://user-images.githubusercontent.com/1153183/61094716-42e83880-a41e-11e9-97fa-a84b533e23b2.png">

After a bit of trial and error, it appears to be caused by having the Call for Speakers field be empty.  Even though it's listed as optional.  When editing an existing event, you get that error if it's left empty.

(Also, you are spewing PHP fatal errors visibly, that's probably not what you want to be doing) :)

**Comment by heiglandreas** [comment]
That has been fixed already but the fix seems not to be deployed yet...

**Comment by svpernova09** [comment]
> That has been fixed already but the fix seems not to be deployed yet...

Just did a deployment.
