### ISSUE TITLE
How long should the session timeout be set for?

### ISSUE THREAD

**Issue by svpernova09** [joindin/joindin-web2#834]
Opened this in a response to https://twitter.com/philipsharp/status/1157293614285905924

`@joindin Can the website timeout be longer than an hour so I don't have to log in again after *every* session of a conference?`

Currently the timeout is set for 1 hour. Should we default to higher to make it easier on users? 5 hours? 6 hours?

**Comment by svpernova09** [comment]
Looking for feedback from @joindin/leadership-team

**Comment by iansltx** [comment]
Where's the timeout set? I'm pretty sure it's just using the default of 24 minutes. https://docs.platform.sh/languages/php/ini.html is how we'd change it.

**Comment by svpernova09** [comment]
> Where's the timeout set to an hour? I'm pretty sure it's just using the default of 24 minutes. https://docs.platform.sh/languages/php/ini.html is how we'd change it.

Based on not setting it here https://github.com/joindin/joindin-platformsh/blob/master/web/.platform.app.yaml it seems like it would be using the 24 minute default. (not sure if that's a PHP default or a Platform.sh)

**Comment by iansltx** [comment]
That'd be a PHP default. Since it's an idle timeout, setting the timeout to 90 minutes should cover someone leaving feedback on each session as it happens (ignoring workshops). If we wanted to include workshops, 4 hours would work.

**Comment by svpernova09** [comment]
I'm 👍 on setting it @ 90 minutes.

**Comment by EliW** [comment]
I would highly suggest something like 4hrs. Or longer.  And/or keep it shorter but use a remember me cookie.  

As conf .org, I want a low barrier to entry to use a rating app.  Asking people to log in more than once a conference.  Is super annoying.  

Honestly I’d really lean towards adding a remember me in general here.  Regardless of the length of session.

**Comment by EliW** [comment]
If I don’t have to log into Facebook or Twitter every time I want to share my deepest secrets with the world.  And let advertisers scrape my data.   I certainly shouldn’t have to do that for rating conference talks.   #2centa

**Comment by beryllium** [comment]
Count me as a vote in favour of having sessions persist a bit longer. Eli's 4 hour suggestion sounds practical, if the system can handle it. (And if it can't handle it ... maybe there's another solution for auth that can factor out that issue altogether?)

**Comment by svpernova09** [comment]
Closed an opened a task as #839

**Comment by svpernova09** [comment]
We've just deployed a change to change the timeout to 4 hours. Please let us know what you think.
