### ISSUE TITLE
Replace Homepage "hot events" with "upcoming events"

### ISSUE THREAD

**Issue by svpernova09** [joindin/joindin-web2#844]
* Change https://github.com/joindin/joindin-web2/blob/master/app/src/Application/ApplicationController.php#L53 from `hot` to `upcoming`
* Create new copy of `app/templates/Event/list-hot-events.html.twig` for `app/templates/Event/list-upcoming-events.html.twig`

**Comment by iansltx** [comment]
"Upcoming" isn't accurate. Recent past events are there as well. Should be "popular" maybe?

**Comment by svpernova09** [comment]
So `upcoming` filter includes past events? that sounds like a bug....

**Comment by iansltx** [comment]
Sorry, misread. That's what I get for looking at this while eating lunch while looking at other things.

**Comment by svpernova09** [comment]
> Sorry, misread. That's what I get for looking at this while eating lunch while looking at other things.

No worries! /me goes back to his own lunch

**Comment by siddhantvirus** [comment]
Hi I would like to take this issue !

**Comment by svpernova09** [comment]
@siddhantvirus you've got it!

Let me know if you need any help!

**Comment by siddhantvirus** [comment]
@svpernova09 I fail to understand , why does the StyleCI build fails

**Comment by svpernova09** [comment]
@siddhantvirus don't worry about StyleCI. I'll leave some comments on the PR for you though.
