### ISSUE TITLE
Add track name to talk detail view

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-web2#871]
Right now it's only visible in the list view. Should be a quick add, provided we don't link-ify the name (there's nowhere to link to at this point anyway).

**Comment by iansltx** [comment]
@abbasCoder51 Go ahead. You should be able to use tracks[0]['track_name'] from the API response for the talk, though you'll need to do an existence check as some talks don't have a track associated. I checked yesterday and all talks either have zero or one track associated so this slight simplification is reliable.

**Comment by warren5236** [comment]
@abbasCoder51 are you still working on this or can I try?

**Comment by iansltx** [comment]
@warren5236 Given that that was from 2019, go ahead.

**Comment by abbasCoder51** [comment]
@warren5236 yeah sure go ahead mate
