### ISSUE TITLE
Use rowspan to properly visualize double-length talks in grid view

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-web2#879]
e.g. https://joind.in/event/phpworld-2019/schedule/grid

This would be useful for conferences that have either double-length workshops or half-length uncon talks running alongside a standard talk length.

Below is an example that I got my adding rowspans and deleting cells manually:

![Double-length talk with rowspans](https://user-images.githubusercontent.com/472804/67522869-25f50f80-f673-11e9-9468-71263aad96b7.png)

**Comment by lfbittencourt** [comment]
Hello! Can you assign this one for me? :-)

**Comment by iansltx** [comment]
@lfbittencourt Done. When should I check in, if I haven't seen a PR from you by then?

**Comment by lfbittencourt** [comment]
@iansltx I'm working on it! I will send the PR as soon as I can.
