### ISSUE TITLE
Timezone error when submitting new event

### ISSUE THREAD

**Issue by gsomoza** [joindin/joindin-web2#893]
I get the error mentioned above when trying to submit a new event.

# Steps to Reproduce
1. Log into an existing Joind.in account
1. Browse to https://joind.in/event/submit
2. Fill in the form, only using required fields
3. Timezone: Europe, Brussels
4. Submit

# Expected Behaviour
Event is submitted

# Actual Behaviour
The form is reloaded and the following message appears in red text above the form:
```
an error occurred while submitting your event: DateTimeZone::__construct(): Unknown or bad timezone (/)
```

**Comment by svpernova09** [comment]
Can you try this again? I wasn't able to reproduce the error.

**Comment by gsomoza** [comment]
Hmm it might be a while before I can try this again myself (swamped).. feel free to close, if it happens again I'll re-open with more details.
