### ISSUE TITLE
Can’t reject event

### ISSUE THREAD

**Issue by e3betht** [joindin/joindin-web2#897]
When I try to reject a pending event, I get an error message that says:

Failed to reject event: [“Database error”]

This has happened on different events (not just one). 

![B35BF02C-D444-4C18-9618-1396D091C44A](https://user-images.githubusercontent.com/1811561/69457306-67401400-0d32-11ea-9f43-0c25d3d73ba9.jpeg)

**Comment by svpernova09** [comment]
This has been resolved. I had forgotten to run a migration when we did a deploy.
