### ISSUE TITLE
GitHub Actions?

### ISSUE THREAD

**Issue by warren5236** [joindin/joindin-web2#912]
[jenkins.joind.in](https://jenkins.joind.in/) is no longer in operation.  Should I set up GitHub Actions for the project?

I'm interested in helping and having actions in place will make me feel better about submitting a PR.  :-)

**Comment by iansltx** [comment]
Absolutely. We were just discussing moving from Travis to Actions; I was going to get that rolling, but if you're ready to build that transition will happen more quickly. PR away, and comment here as you have questions.
