### ISSUE TITLE
Trying to join using Twitter/Facebook

### ISSUE THREAD

**Issue by Sjors1985** [joindin/joindin-web2#922]
At the moment, it is not possible to join Joind using Twitter / X or Facebook. There are some buttons available at the index, but both buttons are giving errors. Twitter / X will create the app and fails afterwards. Facebook will show an error-message directly. 

Is this something, which can be fixed? If not, I guess it is better to remove both buttons.

**Comment by heiglandreas** [comment]
Thanks for letting us know!

Due to the past shitstorm on "twitter" at least that one will not be fixed.

But I assume removing both is the best option here.

**Comment by Sjors1985** [comment]
I completely understand the choice. If you want, I can create a PR later this week.
